### PR TITLE
CHORE docker-compose for Developer Productivity

### PR DESCRIPTION
**Pull request by cantremember**
based upon @altenorjr 's work in https://github.com/joylifeinc/registry_service/pull/546

https://joylife.slack.com/archives/C5J4S3N03/p1651631134156609

this is a starting point.  it's an aggregate of resources, some light doco, and 4 yarn tasks.  both @altenorjr and @PRossetti have put together home-rolled solutions much like this one

the *Big Questions:*

- does it work on your machine?
- would you prefer the API / naming was different?
- what are the "useful" command line tasks for a tool like this?
- did i miss anything from Commerce setup?
- where should this tooling live?

### CODE REVIEW

**Review by PRossetti — APPROVED** [review]
This looks very good!

**Comment by pileofrocks** [comment]
screenshot

**Comment by pileofrocks** [comment]
> I'm not advocating for the code in the PR above to be added to server-core, to be clear, but something more thought-out and generic
btw I thought this was a thread about alt's PR still

**Review by pileofrocks — APPROVED** [review]
No comment on this from since it's a tool I'm likely not even gonna use in the short-term anyway

**Comment by cantremember** [comment]
@pileofrocks 👌 on the no-comment

> it's a tool I'm likely not even gonna use in the short-term anyway

yes, but as i've discovered with trying to make our standard Postgres processes run nicely on top of Docker, there are certain conventions that will need to be established RE: usernames, etc.  if we start adopting conventions, they'll be in alignment with this tooling

once tooling has been put into place, it'll be *caveat emptor* for any Devs following their own conventions

**Comment by cantremember** [comment]
has been re-constituted into https://github.com/joylifeinc/server-core/pull/144

**Pull request closed without merging**
